
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package yu.ac.ns.ftn.informatika.ws.hello;

import java.util.logging.Logger;

import yu.ac.ns.ftn.informatika.ws.hello.types.RequestMissType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jan 23 09:13:16 CET 2009
 * Generated source version: 2.1.3
 * 
 */
@javax.ejb.Stateless
@javax.jws.WebService(
                      serviceName = "HelloDocumentService",
                      portName = "HelloDocumentPort",
                      targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/hello",
                      endpointInterface = "yu.ac.ns.ftn.informatika.ws.hello.HelloDocument")
                      
public class HelloDocumentImpl implements HelloDocument {

    private static final Logger LOG = Logger.getLogger(HelloDocumentImpl.class.getName());

    /* (non-Javadoc)
     * @see yu.ac.ns.ftn.informatika.ws.hello.HelloDocument#sayHelloMiss(yu.ac.ns.ftn.informatika.ws.hello.types.RequestMissType  requestMiss )*
     */
    public java.lang.String sayHelloMiss(RequestMissType requestMiss) { 
        LOG.info("Executing operation sayHelloMiss");
        System.out.println(requestMiss);
        
        return "Hello miss " + requestMiss.getFirstName() + " " + requestMiss.getLastName();
    }

}
