package com.xml2017.centralna_banka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-07T00:22:48.098+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.xml2017.com/centralna_banka", name = "CentralnaBankaPortType")
@XmlSeeAlso({generated.ObjectFactory.class, com.xml2017.schema.mt102.ObjectFactory.class, com.xml2017.schema.mt103.ObjectFactory.class, com.xml2017.schema.tipovi_podataka.ObjectFactory.class, com.xml2017.schema.mt910.ObjectFactory.class, com.xml2017.schema.mt900.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CentralnaBankaPortType {

    @WebMethod(operationName = "MT103ReceiveCB")
    @WebResult(name = "mt900", targetNamespace = "http://www.xml2017.com/schema/mt900", partName = "mt900")
    public com.xml2017.schema.mt900.Mt900 mt103ReceiveCB(
        @WebParam(partName = "mt103", name = "mt103", targetNamespace = "http://www.xml2017.com/schema/mt103")
        com.xml2017.schema.mt103.Mt103 mt103
    ) throws RTGSFault;

    @WebMethod(operationName = "MT102ReceiveCB")
    @WebResult(name = "mt900", targetNamespace = "http://www.xml2017.com/schema/mt900", partName = "mt900")
    public com.xml2017.schema.mt900.Mt900 mt102ReceiveCB(
        @WebParam(partName = "mt102", name = "mt102", targetNamespace = "http://www.xml2017.com/schema/mt102")
        com.xml2017.schema.mt102.Mt102 mt102
    ) throws ClearingFault;
}
