//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.08 at 08:16:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xml2017.com/schema/mt900", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xmlwebservisi2016.firma.model.jaxb.mt900;
