package com.xmlwebservisi2016.firma.banka_import;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-09T02:11:16.248+02:00
 * Generated source version: 2.6.5
 * 
 */
@WebService(targetNamespace = "http://www.xml2017.com/banka", name = "Banka")
@XmlSeeAlso({com.xmlwebservisi2016.firma.model.jaxb.prenos.ObjectFactory.class, com.xmlwebservisi2016.firma.model.jaxb.mt102.ObjectFactory.class, com.xmlwebservisi2016.firma.model.jaxb.mt103.ObjectFactory.class, com.xmlwebservisi2016.firma.model.jaxb.izvod.ObjectFactory.class, ObjectFactory.class, com.xmlwebservisi2016.firma.model.jaxb.tipovi_podataka.ObjectFactory.class, com.xmlwebservisi2016.firma.model.jaxb.zahtev.ObjectFactory.class, com.xmlwebservisi2016.firma.model.jaxb.mt910.ObjectFactory.class})
public interface Banka {

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "izvod", targetNamespace = "http://www.xml2017.com/schema/izvod", partName = "izvod")
    public com.xmlwebservisi2016.firma.model.jaxb.izvod.Izvod preuzimanjeIzvoda(
            @WebParam(partName = "zahtev", name = "zahtev-za-izvod", targetNamespace = "http://www.xml2017.com/schema/zahtev")
                    com.xmlwebservisi2016.firma.model.jaxb.zahtev.ZahtevZaIzvod zahtev
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "odgovor-na-placanje", targetNamespace = "http://www.xml2017.com/banka", partName = "odgovor")
    public boolean slanjeNalogaZaPlacanje(
            @WebParam(partName = "nalog", name = "nalog-za-prenos", targetNamespace = "http://www.xml2017.com/schema/prenos")
                    com.xmlwebservisi2016.firma.model.jaxb.prenos.NalogZaPrenos nalog
    );

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "rtgsBanka", targetNamespace = "http://www.xml2017.com/banka", className = "com.xml2017.banka.RtgsBanka")
    public void rtgsBanka(
            @WebParam(name = "mt103", targetNamespace = "")
                    com.xmlwebservisi2016.firma.model.jaxb.mt103.Mt103 mt103,
            @WebParam(name = "mt910", targetNamespace = "")
                    com.xmlwebservisi2016.firma.model.jaxb.mt910.Mt910 mt910
    );

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "clearSettleBanka", targetNamespace = "http://www.xml2017.com/banka", className = "com.xml2017.banka.ClearSettleBanka")
    public void clearSettleBanka(
            @WebParam(name = "mt102", targetNamespace = "")
                    com.xmlwebservisi2016.firma.model.jaxb.mt102.Mt102 mt102,
            @WebParam(name = "mt910", targetNamespace = "")
                    com.xmlwebservisi2016.firma.model.jaxb.mt910.Mt910 mt910
    );
}
