
package com.xml2017.centralna_import;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-09T11:28:29.017+02:00
 * Generated source version: 2.6.5
 */

@WebFault(name = "odgovor-na-placanje", targetNamespace = "http://www.xml2017.com/centralna_banka")
public class RTGSFault extends Exception {
    
    private boolean odgovorNaPlacanje;

    public RTGSFault() {
        super();
    }
    
    public RTGSFault(String message) {
        super(message);
    }
    
    public RTGSFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RTGSFault(String message, boolean odgovorNaPlacanje) {
        super(message);
        this.odgovorNaPlacanje = odgovorNaPlacanje;
    }

    public RTGSFault(String message, boolean odgovorNaPlacanje, Throwable cause) {
        super(message, cause);
        this.odgovorNaPlacanje = odgovorNaPlacanje;
    }

    public boolean getFaultInfo() {
        return this.odgovorNaPlacanje;
    }
}
