
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package yu.ac.ns.ftn.informatika.ws.address;

import java.util.Vector;

import yu.ac.ns.ftn.informatika.ws.address.types.ContactType;
import yu.ac.ns.ftn.informatika.ws.address.types.ContactsType;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jan 23 09:45:35 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.ejb.Stateless
@javax.jws.WebService(
                      serviceName = "AddressBookService",
                      portName = "AddressBookPort",
                      targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/address",
                      endpointInterface = "yu.ac.ns.ftn.informatika.ws.address.AddressBook")
                      
public class AddressBookImpl implements AddressBook {
	
	private Vector<ContactType> contacts = new Vector<ContactType>();

    /* (non-Javadoc)
     * @see yu.ac.ns.ftn.informatika.ws.address.AddressBook#addContact(yu.ac.ns.ftn.informatika.ws.address.types.ContactType  contact )*
     */
    public void addContact(ContactType contact) {
    	contacts.add(contact);
		System.out.println("=====addContact invoked======");
    }

    /* (non-Javadoc)
     * @see yu.ac.ns.ftn.informatika.ws.address.AddressBook#getContactByName(java.lang.String  firstName ,)java.lang.String  lastName )*
     */
    public yu.ac.ns.ftn.informatika.ws.address.types.ContactType getContactByName(java.lang.String firstName,java.lang.String lastName) { 
    	System.out.println("=====getContactByName invoked======");
		for(ContactType contact : contacts) 
			if(contact.getFirstName().equals(firstName) && contact.getLastName().equals(lastName))
				return contact;
		
		//if reach this, not found
		return null;
    }

    /* (non-Javadoc)
     * @see yu.ac.ns.ftn.informatika.ws.address.AddressBook#getContact(int  index )*
     */
    public yu.ac.ns.ftn.informatika.ws.address.types.ContactType getContact(int index) { 
    	System.out.println("=====getContact invoked====");
		if(index < contacts.size())
			return contacts.get(index);
		else
			return null;
    }

    /* (non-Javadoc)
     * @see yu.ac.ns.ftn.informatika.ws.address.AddressBook#getAllContacts(*
     */
    public ContactsType getAllContacts() {
    	System.out.println("=====getAllContacts invoked====");
    	ContactsType retVal = new ContactsType();
    	retVal.getValue().addAll(contacts);
    	
    	return retVal;
    }

}
