package yu.ac.ns.ftn.informatika.ws.address;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import yu.ac.ns.ftn.informatika.ws.address.types.ContactType;
import yu.ac.ns.ftn.informatika.ws.address.types.ObjectFactory;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Jan 23 09:45:35 CET 2009
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/address", name = "AddressBook")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AddressBook {

    @WebMethod
    public void addContact(@WebParam(partName = "contact", name = "contact") ContactType contact);

    @WebResult(name = "result", targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/address", partName = "result")
    @WebMethod
    public ContactType getContactByName(@WebParam(partName = "firstName", name = "firstName") String firstName,
    									@WebParam(partName = "lastName", name = "lastName") String lastName);

    @WebResult(name = "result", targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/address", partName = "result")
    @WebMethod
    public ContactType getContact(@WebParam(partName = "index", name = "index") int index);

    @WebResult(name = "result", targetNamespace = "http://informatika.ftn.ns.ac.yu/ws/address", partName = "result")
    @WebMethod
    public yu.ac.ns.ftn.informatika.ws.address.types.ContactsType getAllContacts();
}
